image: node:latest

stages:
  - prerequisites
  - checks
  - deploy

install:
  stage: prerequisites
  script:
    - yarn install --cache-folder .yarn

  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 30 mins
    paths:
      - .yarn/
      - node_modules/

test:
  stage: checks
  needs: ['install']

  script:
    - yarn run test
  dependencies:
    - install

build:
  stage: checks
  needs: ['install']

  script:
    - yarn build
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 30 mins
    paths:
      - **
  dependencies:
    - install

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish -f --access public
