image: node:latest

stages:
  - prerequisites
  - checks
  - deploy

install:
  stage: prerequisites
  script:
    - npm install

  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 30 mins
    paths:
      - node_modules/

test:
  stage: checks
  needs: ['install']

  script:
    - npm run test
  dependencies:
    - install

lint:
  stage: checks
  needs: ['install']

  script:
    - npm run lint
  dependencies:
    - install

build:
  stage: checks
  needs: ['install']

  script:
    - npm run build
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 30 mins
    paths:
      - dist
  dependencies:
    - install

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm login
    - npm publish --access public
